sudo: false

language: node_js

node_js:
  - '6.10'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g gulp
  - npm install --ignore-scripts # avoid triggering npm prepublish script (which runs on npm install), running the tests twice during the build
  - npm run build

cache:
  directories:
    - node_modules

script:
 - npm run test
 - echo "Your live demo url, if everything went well, should be https://coveo.github.io/react-vapor/$TRAVIS_PULL_REQUEST_BRANCH/"

after_success:
 - npm run report-coverage

after_script:
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run docs && node create-live-demo.js; fi' # run this line on pull request builds only
