sudo: required

language: node_js

node_js:
    - '12.3'

addons:
    chrome: stable

env:
    global:
        - AWS_ACCESS_KEY_ID=AKIAYKDJLZITTS3QHYP2

before_install:
    - eval "$(ssh-agent -s)" #start the ssh agent
    - openssl aes-256-cbc -K $encrypted_6a1e0d13907f_key -iv $encrypted_6a1e0d13907f_iv -in id_rsa.enc -out travis-deploy-key -d
    - chmod 600 travis-deploy-key # this key should have push access
    - ssh-add travis-deploy-key

install:
    - npm install -g lerna
    - lerna bootstrap --no-ci
    - npm install

cache:
    directories:
        - node_modules

script:
    - lerna run build
    - lerna run docs
    - lerna run test
    - lerna run test:compile # to catch any lint or compile errors, compile tests through webpack prior to running test suites with karma (karma always exit its process with 0)

after_script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./create-live-demo.sh; fi' # run this line on pull request builds only

after_success:
    - lerna run report-coverage
    - mkdir -p "packages/vapor/deploy/$TRAVIS_TAG"
    - cp -a packages/vapor/dist/. "packages/vapor/deploy/$TRAVIS_TAG"

deploy:
    - provider: s3
      skip_cleanup: true
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key:
          secure: 'FCCwGIggMIPz/dk3nDyICAua5KCxHQ9t1gc0jvw5P6zVS/l2GYzwNUbLNz1lBfikvcDS/2NlGpl5Znd/4lBQuiGUEniIgLlbpEHmHyHCV/GPYLYAgWNweCdwUF5bHRygj32I6zIyOAp1EX5jlh39Xcci9hkaGLMWhd3i4XsPxQYYCAhvuL7hw5IljpUiQPOuwJxIU7yHc87JtJkQ/h98qRIXwvwDoNIKPMeRdI1pHTJFUXPn8+4nxavqngXWqOtzdv3+NgTBQiPl+t0k0u2+pUU7C+zXSN2oSZ+qTOb67oEJzTJ733p7VUhFBfEWBko36PpMV+4xm1VXlMzs621E+8GiSFcy07GQhFcZ3YTSl+/u5JgXQJmIuj7dcS+DUsZ28dCTh/w+BEThchpFkwvrkn2hHYUmmB/XEHRWNJ/7lc31dz//gXlspq2GTQqmnuxORfobLd2Oi+bqnDYB4BV4QTxitrZu9ou3UKg/zGevpGgKmAzhwLAQSDvkCWfJs4z/k7gg9F85/ah1Aivjmo5RypSU7KMtqkfDRv/xiL9W8RnuEELK5VQJ1oJmaMAtfcHtV8hSCQiqoV0ECXuA3DU3FcaKThPV/49LxXkx+g2M3CA1AzPW5tUjmcr9cKAcZY+YcWhKLs2aIiuBQkyATw/Uo9VHI0cBqItaWYa6Uh7DMu0='
      bucket: coveo-prd-jsadmin
      local-dir: packages/react-vapor/docs/dist
      upload-dir: react-vapor
      acl: public_read

    - provider: s3
      skip_cleanup: true
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key:
          secure: 'FCCwGIggMIPz/dk3nDyICAua5KCxHQ9t1gc0jvw5P6zVS/l2GYzwNUbLNz1lBfikvcDS/2NlGpl5Znd/4lBQuiGUEniIgLlbpEHmHyHCV/GPYLYAgWNweCdwUF5bHRygj32I6zIyOAp1EX5jlh39Xcci9hkaGLMWhd3i4XsPxQYYCAhvuL7hw5IljpUiQPOuwJxIU7yHc87JtJkQ/h98qRIXwvwDoNIKPMeRdI1pHTJFUXPn8+4nxavqngXWqOtzdv3+NgTBQiPl+t0k0u2+pUU7C+zXSN2oSZ+qTOb67oEJzTJ733p7VUhFBfEWBko36PpMV+4xm1VXlMzs621E+8GiSFcy07GQhFcZ3YTSl+/u5JgXQJmIuj7dcS+DUsZ28dCTh/w+BEThchpFkwvrkn2hHYUmmB/XEHRWNJ/7lc31dz//gXlspq2GTQqmnuxORfobLd2Oi+bqnDYB4BV4QTxitrZu9ou3UKg/zGevpGgKmAzhwLAQSDvkCWfJs4z/k7gg9F85/ah1Aivjmo5RypSU7KMtqkfDRv/xiL9W8RnuEELK5VQJ1oJmaMAtfcHtV8hSCQiqoV0ECXuA3DU3FcaKThPV/49LxXkx+g2M3CA1AzPW5tUjmcr9cKAcZY+YcWhKLs2aIiuBQkyATw/Uo9VHI0cBqItaWYa6Uh7DMu0='
      bucket: coveo-prd-jsadmin
      local-dir: packages/vapor/deploy
      upload-dir: styleguide
      acl: public_read
      on:
          tags: true
          repo: coveo/react-vapor

after_deploy:
    - node invalidate-cloudfront.js

notifications:
    email:
        on_success: never
        on_failure: never
